[build]
  command = "ng build --configuration production"
  publish = "dist/baghchi-admin-fe/browser"

[[plugins]]
  package = "@netlify/angular-runtime"

[[plugins.inputs.client_only_routes]]
  path = "/webrtc"
